### ISSUE TITLE
Making RStudio rebuild .so and .o files?

### ISSUE THREAD

**Issue by eeholmes** [atsa-es/marssTMB#3]
@ericward-noaa When I change .hpp files, the .so and .o files don't get rebuild when I hit 'Install' and rebuild the package the .so and .o files don't rebuild. What am I doing wrong? Thanks!!

**Comment by ericward-noaa** [comment]
The .o and .so files seem to be only built for the .cpp files, not .h files. Most of the packages I've worked with previously have had the main code in the .cpp files, but this w/TMBtools puts most in the headers. I think this is ok? 

Anyway, I can get the .o and .so files rebuilt in RStudio by doing -> More -> Clean and Install. Or from the command line, 
pkgbuild::compile_dll()
